site_name: chemdiagrams
site_url: https://Tonner-Zech-Group.github.io/chem-diagrams
repo_url: https://github.com/Tonner-Zech-Group/chem-diagrams

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy

nav:
  - Home: index.md
  - Examples: examples.md
  - API Reference: api/  # populated by the gen script

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: pip install -r requirements-docs.txt
      - run: mkdocs gh-deploy --force