
"""Constants for plotting the energy diagram"""

MAX_WIDTH = 7
HEIGHT = 3
X_SCALE = 0.8 # Inches per x-tick
WIDTH_PLATEAU = 0.5
DISTANCE_TEXT_DIFFBAR = 0.02
DISTANCE_NUMBER_LINE = 0.09
DISTANCE_LABEL_LINE = 0.12
DISTANCE_NUMBER_NUMBER = 0.135

DEFAULT_X_MARGINS = (-0.5, 0.5)
DEFAULT_Y_MARGINS = (-0.1, 0.15)
 